### ISSUE TITLE
byte[]参数如何获取和修改

### ISSUE THREAD

**Issue by xavieryang007** [axhlzy/Il2CppHookScripts#14]
U3D函数参数是byte[]  应该如何hook查看和修改

**Comment by xavieryang007** [comment]
通过IDA发现，byte[]的长度是基址偏移24

**Comment by HimekoEx** [comment]
数组（[]）类型就是Il2cppArray，直接拿来用就行了

话说你这个脚本写的好杂啊...看不懂@axhlzy
