### ISSUE TITLE
请问下 find_method要查找 Dictionary 实例化的函数地址 该如何写

### ISSUE THREAD

**Issue by GcrazyX** [axhlzy/Il2CppHookScripts#15]
请问下 find_method要查找 Dictionary 实例化的函数地址 该如何写

**Comment by axhlzy** [comment]
没太懂啥意思

**Comment by GcrazyX** [comment]
就是模板类  或者模板函数  比如 static int Send<TProtocol>(Protocol<TProtocol> protocol) 
find_method 查找的函数名 直接写Send找不到地址

**Comment by GcrazyX** [comment]
finish
