### ISSUE TITLE
建议把namespace搜索且断点也加上

### ISSUE THREAD

**Issue by 2wong** [axhlzy/Il2CppHookScripts#18]
范围搜索这个还是用的比较多啊，image搜索下的方法比较多的时候，缩小范围可以namespace[抱拳]

**Comment by axhlzy** [comment]
妥的 妥的 后续空了给加上

**Comment by axhlzy** [comment]
B() 的 args[0] ImagePtr or ImageName ,arg[1] 用来传递 namespace

namespace没法直接去找，这里想着是用image去遍历class，然后class的namespace用作筛选

**Comment by 2wong** [comment]
> B() 的 args[0] ImagePtr or ImageName ,arg[1] 用来传递 namespace
> 
> namespace没法直接去找，这里想着是用image去遍历class，然后class的namespace用作筛选

是的，在你之前的版本Ufun.js中我也是筛选hook的，现在的ts看着有点懵 - - ，刚试过了完全ok 感谢！
