### ISSUE TITLE
你好，我用模拟器找不到libil2cpp.so，用非root真机修改smali的方式，加载frida so成功，也监听端口了，就是一附加就崩溃

### ISSUE THREAD

**Issue by darkness-A** [axhlzy/Il2CppHookScripts#20]
你好，我用模拟器找不到libil2cpp.so，用非root真机修改smali的方式，加载frida so成功，也监听端口了，就是一附加就崩溃

**Comment by axhlzy** [comment]
附个apk链接 我瞅瞅

**Comment by darkness-A** [comment]
https://cdn-and-ct2.ghzs.com/upgrade/channel/2022/12/21/com.gh.gamecenter_5.15.3_653_GH_201_1671607956.apk
在光环助手下载的，燃烧意志全局加速版

**Comment by darkness-A** [comment]
这是我的操作过程https://www.52pojie.cn/thread-1736255-1-1.html

**Comment by ImKK666** [comment]
> 这是我的操作过程https://www.52pojie.cn/thread-1736255-1-1.html

帖子G了

**Comment by suzuke** [comment]
> 你好，我用模拟器找不到libil2cpp.so，用非root真机修改smali的方式，加载frida so成功，也监听端口了，就是一附加就崩溃

用模擬器的話要記得加上--realm emulated

**Comment by darkness-A** [comment]
还有这个操作吗，我去试一下，这样就能找到so模块了吗

**Comment by darkness-A** [comment]
> > 你好，我用模拟器找不到libil2cpp.so，用非root真机修改smali的方式，加载frida so成功，也监听端口了，就是一附加就崩溃
> 
> 用模擬器的話要記得加上-realm emulated

是给frida加这个参数吗？

**Comment by darkness-A** [comment]
> > 这是我的操作过程https://www.52pojie.cn/thread-1736255-1-1.html
> 
> 帖子G了

好像还没过审核、
![b3251b03702efc53b91057ec75b46d08_135230rvz0r0kqztnqrv5x](https://user-images.githubusercontent.com/22480057/212463130-cdb55fda-3b46-480a-9b5a-d3af670a1042.png)
![66adc3ca9bb288c663c9215035f0b7ff_135403odb0j0ojdjoeduga](https://user-images.githubusercontent.com/22480057/212463135-23e89de8-5384-4baa-9871-35983f788861.png)

**Comment by axhlzy** [comment]
你这样用吧 
frida -FU -l ../_Ufunc.js，刚才我测试了一下没问题
spawn确实有时候会有问题，还是用attach稳点

**Comment by darkness-A** [comment]
> 

你的运行环境是啥，真机吗？root环境还是？

**Comment by axhlzy** [comment]
piex4 root

**Comment by axhlzy** [comment]
你用的 gadget吗 ？ 
你先 frida -FU 别带脚本，然后附加上程序正常跑起来以后 再去frida -FU -l ../_Ufunc.js，也许能行

**Comment by darkness-A** [comment]
> > 
> 
> 你的运行环境是啥，真机吗？root环境还是？


你的运行环境是啥，真机吗？root环境还是？



> 你用的 gadget吗 ？ 你先 frida -FU 别带脚本，然后附加上程序正常跑起来以后 再去frida -FU -l ../_Ufunc.js，也许能行

对，我是加载的这个so，我试试看

**Comment by darkness-A** [comment]
> frida -FU -l ../_Ufunc.js

直接提示No frontmost application on LON AL0，我目前应用是黑的

**Comment by darkness-A** [comment]
> 你用的 gadget吗 ？ 你先 frida -FU 别带脚本，然后附加上程序正常跑起来以后 再去frida -FU -l ../_Ufunc.js，也许能行

上面那个大佬写的加-realm emulated参数，他是说给模拟器加吗？

**Comment by darkness-A** [comment]
![image](https://user-images.githubusercontent.com/22480057/212463773-e24806c9-1a9e-4ccd-a6f3-e9f9ed107897.png)

**Comment by axhlzy** [comment]
> > 你用的 gadget吗 ？ 你先 frida -FU 别带脚本，然后附加上程序正常跑起来以后 再去frida -FU -l ../_Ufunc.js，也许能行
> 
> 上面那个大佬写的加-realm emulated参数，他是说给模拟器加吗？

这个我不知道欸 




> ![image](https://user-images.githubusercontent.com/22480057/212463773-e24806c9-1a9e-4ccd-a6f3-e9f9ed107897.png)

搞这些玩意儿还是建议搞一台root的piex可以避免很多不必要的麻烦

**Comment by darkness-A** [comment]
> > 你好，我用模拟器找不到libil2cpp.so，用非root真机修改smali的方式，加载frida so成功，也监听端口了，就是一附加就崩溃
> 
> 用模擬器的話要記得加上-realm emulated

你好，能说一下你用的什么环境吗

**Comment by suzuke** [comment]
> > > 你好，我用模拟器找不到libil2cpp.so，用非root真机修改smali的方式，加载frida so成功，也监听端口了，就是一附加就崩溃
> > 
> > 
> > 用模擬器的話要記得加上-realm emulated
> 
> 你好，能说一下你用的什么环境吗

模擬器使用Frida的時候，如果要可以分析libil2cpp.so，就必須在frida後面加上--realm emulated (原本回復少了一個-)
因為模擬器並非直接使用libil2cpp.so(arm)，而是透過libhoudini.so進行指令轉譯，所以如果不加上--realm emulated的話
只能分析到libhoudini.so。
PS.另外加上--realm emulated會導致java層的分析失敗。

**Comment by darkness-A** [comment]
> > > > 你好，我用模拟器找不到libil2cpp.so，用非root真机修改smali的方式，加载frida so成功，也监听端口了，就是一附加就崩溃
> > > 
> > > 
> > > 用模擬器的話要記得加上-realm emulated
> > 
> > 
> > 你好，能说一下你用的什么环境吗
> 
> 模擬器使用Frida的時候，如果要可以分析libil2cpp.so，就必須在frida後面加上--realm emulated (原本回復少了一個-) 因為模擬器並非直接使用libil2cpp.so(arm)，而是透過libhoudini.so進行指令轉譯，所以如果不加上--realm emulated的話 只能分析到libhoudini.so。 PS.另外加上--realm emulated會導致java層的分析失敗。

谢谢你，我等会试试

**Comment by darkness-A** [comment]
> > > > 你好，我用模拟器找不到libil2cpp.so，用非root真机修改smali的方式，加载frida so成功，也监听端口了，就是一附加就崩溃
> > > 
> > > 
> > > 用模擬器的話要記得加上-realm emulated
> > 
> > 
> > 你好，能说一下你用的什么环境吗
> 
> 模擬器使用Frida的時候，如果要可以分析libil2cpp.so，就必須在frida後面加上--realm emulated (原本回復少了一個-) 因為模擬器並非直接使用libil2cpp.so(arm)，而是透過libhoudini.so進行指令轉譯，所以如果不加上--realm emulated的話 只能分析到libhoudini.so。 PS.另外加上--realm emulated會導致java層的分析失敗。
我下载的frida服务端好像没有这个选项
Unknown option --realm
Run './frida --help' to see a full list of available command line options.

**Comment by Tinhone** [comment]
新手刚经历过一次类似的事情，通过修改模拟器文件改变游戏运行架构解决了下面的报错，并且不影响 JAVA 层相关代码的运行。希望这能够对后来的朋友们有所帮助🙏
参考链接:[《网易mumu、雷电模拟器，修改游戏运行架构》](https://zhuanlan.zhihu.com/p/540151136)
```
Error: unable to find module 'libil2cpp.so'
    at value (frida/runtime/core.js:339)
    at get module (...
```

**Comment by darkness-A** [comment]
> 新手刚经历过一次类似的事情，通过修改模拟器文件改变游戏运行架构解决了下面的报错，并且不影响 JAVA 层相关代码的运行。希望这能够对后来的朋友们有所帮助🙏 参考链接:[《网易mumu、雷电模拟器，修改游戏运行架构》](https://zhuanlan.zhihu.com/p/540151136)
> 
> ```
> Error: unable to find module 'libil2cpp.so'
>     at value (frida/runtime/core.js:339)
>     at get module (...
> ```

那可太牛了，我现在的方法影响使用java代码，你这个好
