### ISSUE TITLE
Frida-Gadget with error Java API not available

### ISSUE THREAD

**Issue by mrkio9** [axhlzy/Il2CppHookScripts#21]
I want to Dump this libil2cpp.so but it has error
```
C:\Users\Admin>frida -l F:\Download\Il2CppHookScripts-ts\Il2CppHookScripts-ts\Il2cppHook\_Ufunc.js -U Gadget
     ____
    / _  |   Frida 16.0.10 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Android Emulator 5556 (id=emulator-5556)

[Android Emulator 5556::Gadget ]-> dumpSo()
------------------------------
[name]:libil2cpp.so
[base]:0x73c0000
[size]:25190400
[path]:/data/app/vn.pg1.vltk1m-iPPlLFi7_LzKT9aWhEB56Q==/lib/arm/libil2cpp.so
------------------------------
Error: Java API not available
    at _checkAvailable (frida/node_modules/frida-java-bridge/index.js:298)
    at perform (frida/node_modules/frida-java-bridge/index.js:203)
    at dump_mem (agent/utils/dumper.ts:22)
    at dump_so (agent/utils/dumper.ts:10)
    at <eval> (<input>:1)
    at eval (native)
```
Please help me if you know

**Comment by mrkio9** [comment]
and sometime, at Newest version, it has crashes, i dont know why but it call Gadget "Connection terminated" when apps want to download or connect to their server. I love this newest version but i have to use old version. hm... still error below

**Comment by axhlzy** [comment]
> I want to Dump this libil2cpp.so but it has error
> 
> ```
> C:\Users\Admin>frida -l F:\Download\Il2CppHookScripts-ts\Il2CppHookScripts-ts\Il2cppHook\_Ufunc.js -U Gadget
>      ____
>     / _  |   Frida 16.0.10 - A world-class dynamic instrumentation toolkit
>    | (_| |
>     > _  |   Commands:
>    /_/ |_|       help      -> Displays the help system
>    . . . .       object?   -> Display information about 'object'
>    . . . .       exit/quit -> Exit
>    . . . .
>    . . . .   More info at https://frida.re/docs/home/
>    . . . .
>    . . . .   Connected to Android Emulator 5556 (id=emulator-5556)
> 
> [Android Emulator 5556::Gadget ]-> dumpSo()
> ------------------------------
> [name]:libil2cpp.so
> [base]:0x73c0000
> [size]:25190400
> [path]:/data/app/vn.pg1.vltk1m-iPPlLFi7_LzKT9aWhEB56Q==/lib/arm/libil2cpp.so
> ------------------------------
> Error: Java API not available
>     at _checkAvailable (frida/node_modules/frida-java-bridge/index.js:298)
>     at perform (frida/node_modules/frida-java-bridge/index.js:203)
>     at dump_mem (agent/utils/dumper.ts:22)
>     at dump_so (agent/utils/dumper.ts:10)
>     at <eval> (<input>:1)
>     at eval (native)
> ```
> 
> Please help me if you know

It is recommended to use a real device instead of an emulator
