### ISSUE TITLE
有指定 Unity 版本的方法吗？

### ISSUE THREAD

**Issue by WankkoRee** [axhlzy/Il2CppHookScripts#22]
尝试`HookPlayerPrefs()`，但是报了6行的`il2cpp: couldn't determine the Unity version, please specify it manually`。

发现是[frida-il2cpp-bridge](https://github.com/vfsfitvnm/frida-il2cpp-bridge)的报错，其开发者给的解决办法是[couldn't determine the Unity version](https://github.com/vfsfitvnm/frida-il2cpp-bridge/issues/149)。

但是因为对本项目各处代码的运行时机不太了解，不知道应该写在哪。

是否有提供或者能够提供指定 Unity 版本的方法？

**Comment by axhlzy** [comment]
尝试使用 master分支下的 老版本ufunc.js 试试
frida-il2cpp-bridge 我也是直接引入的项目，不太方便修改它的源码

**Comment by axhlzy** [comment]
[frida-il2cpp-bridge](https://github.com/vfsfitvnm/frida-il2cpp-bridge) 开发者给的办法我后续遇到 那些出问题的版本在添加上去把  或者你先用 AssetStudioGUI 查看一下你当前的unity版本  试试他的这个做法？

**Comment by WankkoRee** [comment]
我直接在`agent/index.ts`下插入其开发者所给代码发现可行。

![image](https://user-images.githubusercontent.com/21287731/227838012-c0d1c7a0-cba9-4411-b464-1ff83fe11197.png)

**Comment by axhlzy** [comment]
嗯 妥当的 我后面更新一下
