### ISSUE TITLE
使用showComponents的时候，参数是对象地址，怎么查看当前场景中所有对象呢

### ISSUE THREAD

**Issue by yujack008** [axhlzy/Il2CppHookScripts#30]
如题，麻烦大佬回复一下，非常感谢

**Comment by axhlzy** [comment]
https://github.com/axhlzy/Il2CppHookScripts/wiki/API#PrintHierarchy

你指的是这个吗 ？

**Comment by yujack008** [comment]
> https://github.com/axhlzy/Il2CppHookScripts/wiki/API#PrintHierarchy
> 
> 你指的是这个吗 ？

PrintHierarchy函数也是需要参数，而这个参数是指的是什么呢？好像没有看到相关说明。还有就是怎么获取这个参数值呢

**Comment by axhlzy** [comment]
抱歉没注意看issues 。。。

获取这个值的地方很多，参数指的是gameobject实例
比如 setActive() OnPointerClick() 再或者 使用 b(methodinfo非静态方法) 得到第一个实例参数，但凡是能通过它拿到gameobject的实例，都可以用作于他的参数
