### ISSUE TITLE
大哥求助!找不到libil2cpp.so

### ISSUE THREAD

**Issue by 1034205079** [axhlzy/Il2CppHookScripts#31]
大佬,我用的你的第一个方法,用的fat 包名 启动的游戏,但是后面发现找不到libil2cpp.so .请教这是怎么回事呀?
![Uploading 屏幕截图 2023-12-13 191515.png…]()

**Comment by 1034205079** [comment]
[M2007J22C::com.zqpgzs.kzysqh.kzys_sw ]-> printExp("die",true)
ReferenceError: printExp is not defined
    at eval (undefined:1:1)
[M2007J22C::com.zqpgzs.kzysqh.kzys_sw ]-> findClass("player")
Error: unable to find module 'libil2cpp.so'
    at Object.value [as getModuleByName] (frida/runtime/core.js:356:1)
    at Function.get module (node_modules/frida-il2cpp-bridge/dist/il2cpp/base.js:66:1)
    at Function.t.get (node_modules/decorator-cache-getter/dist/index.js:7:1)
    at Function.r (node_modules/frida-il2cpp-bridge/dist/il2cpp/api.js:444:1)
[M2007J22C::com.zqpgzs.kzysqh.kzys_sw ]->

**Comment by 1034205079** [comment]
![Uploading ss.png…]()

**Comment by 1034205079** [comment]
![ss](https://github.com/axhlzy/Il2CppHookScripts/assets/47485084/bc4901d5-2779-467f-8782-a4e480debcf0)

**Comment by axhlzy** [comment]
你先直接打开这个apk文件去看看是unity游戏吗？
il2cpp类型的还是dll类型的，再或者是其他游戏引擎的 ？

**Comment by 1034205079** [comment]
> 你先直接打开这个apk文件去看看是unity游戏吗？ il2cpp类型的还是dll类型的，再或者是其他游戏引擎的 ？

大佬，我用手机连接就可以了。手机是晓龙835，安卓9的miui系统。貌似有些函数用不了，像：

[i() == list_images : 列出所有的 Images](https://github.com/axhlzy/Il2CppHookScripts/wiki/API#list_images)
[c() == list_classes : 列出所有的 Classes](https://github.com/axhlzy/Il2CppHookScripts/wiki/API#list_classes)

请问您，有无其他的函数可以看呢？谢谢

**Comment by axhlzy** [comment]
启动后在使用fat试试
