### ISSUE TITLE
can I use this on memuPlay

### ISSUE THREAD

**Issue by vanhvungve** [axhlzy/Il2CppHookScripts#35]

**Comment by axhlzy** [comment]
The x64 PC emulator running Android arm32/arm64 uses `Houdini`.
transcoding, it will cause `libil2cpp.so` not to be found directly in memory, and then it's not open source, so it's recommended to use the real machine.

**Comment by vanhvungve** [comment]
> The x64 PC emulator running Android arm32/arm64 uses `Houdini`. transcoding, it will cause `libil2cpp.so` not to be found directly in memory, and then it's not open source, so it's recommended to use the real machine.

![image](https://github.com/axhlzy/Il2CppHookScripts/assets/31364958/c1dda95f-c8f6-4385-a5b4-35003c0ab1dd)
use --realm=emulated option it will work. after using B() some error appears and when using b() function for Methodptr-soaddr method it becomes unresponsive and neither does the application

**Comment by axhlzy** [comment]
Give me a download link and I'll try it out

**Comment by vanhvungve** [comment]
> Give me a download link and I'll try it out

[here](https://down.x7sy.com/game/android/5/303/10069_5_1-0-0_20240125181126_halo.apk)

**Comment by axhlzy** [comment]
![1711447987923](https://github.com/axhlzy/Il2CppHookScripts/assets/20512058/1d688d23-d2db-4dcf-b199-6410800859a5)

It works on xiaomi 8.

Get a rooted real machine to play with, before you're tortured by inexplicable circumstances

**Comment by axhlzy** [comment]
I think I remember having this problem before, did you confirm that you are using the latest version of the code? Or change the frida-tools version.

**Comment by axhlzy** [comment]
![1711448372329](https://github.com/axhlzy/Il2CppHookScripts/assets/20512058/29c4b865-0fd8-4786-ac3d-60addae66523)

I'm using this version now

**Comment by vanhvungve** [comment]
i use version 16.0.9
