### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Kn0wns** [axhlzy/Il2CppHookScripts#37]
仅 `import "il2cpp-hooker"` 引入项目编译
![image](https://github.com/user-attachments/assets/76fc3117-a87c-4668-9a1d-5eb643445271)

**Comment by axhlzy** [comment]
我也不太了解ts编译这一块，但是你这里遇到的这个问题可能是 [tsconfig.json](https://github.com/axhlzy/Il2CppHookScripts/blob/ts/Il2cppHook/tsconfig.json) 里面的配置有问题

**Comment by Kn0wns** [comment]
修改为 esBuild 进行编译, 注入脚本也会提示错误, 用 frida-compile 就会提示一堆编译错误
![image](https://github.com/user-attachments/assets/69af78bb-e896-4bc4-8efa-e9a3d107ac07)

看来是无法引入到项目里进行使用了

**Comment by axhlzy** [comment]
https://github.com/axhlzy/Il2CppHookScripts/blob/ts/Il2cppHook/agent/index.ts
这个项目写的时候就没有把它当成一个库来写的
你可以考虑直接在这里写代码编译运行就可以了

**Comment by Kn0wns** [comment]
我是引入到自己项目操作的
