### ISSUE TITLE
目标app有检测frida，怎么进行反检测？

### ISSUE THREAD

**Issue by yorling** [axhlzy/Il2CppHookScripts#38]
目标app在libmsaoaidsec.so中有对frida进行检测与闪退，用fat命令无法正常启动app。可以通过禁止加载该.so来绕过检测，这个要怎么用fat命令实现？

**Comment by 350030173** [comment]
如果“禁止加载该.so来绕过检测”有效，那你直接用frida hook dlopen不让它加载就好了嘛，前提是你说的“可以通过禁止加载该.so来绕过检测”有效

**Comment by axhlzy** [comment]
这只是一个解析il2cpp的脚本哦  反检测不属于这个项目的话题
